### ISSUE TITLE
Datasets use the same URL? // How to download a non-competition datasets with the kaggle cli?

### ISSUE THREAD

**Issue by sck** [Pawandeep-prog/keras-seq2seq-chatbot-with-attention#1]
Both datasets in the README point to the same URL
```
    glove6b 50d : https://www.kaggle.com/watts2/glove6b50dtxt
    cornell movie : https://www.kaggle.com/watts2/glove6b50dtxt
```

Also: I tried downloading the first dataset like so with the kaggle-cli but I get a 404.  I have no idea how to specify a dataset that's not from a competition in the kaggle cli:

```
$ kaggle datasets download watts2/datasets -f glove6b50dtxt
404 - Not Found
```

**Comment by Pawandeep-prog** [comment]
I've updated readme file 
I'm sorry for that silly 😔 mistake.

cornell dataset https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html

glove 6b 50d http://nlp.stanford.edu/data/glove.6B.zip 

hope this should solve now
