### ISSUE TITLE
 I have some questions need your help

### ISSUE THREAD

**Issue by Turing-dz** [Pawandeep-prog/keras-seq2seq-chatbot-with-attention#2]
could you share me your file about chatbot.h5,because my results too bad. I just want to debug the project in my compute.  please forgive my bad english.  hope your response ,thanks.

**Comment by Pawandeep-prog** [comment]
> could you share me your file about chatbot.h5,because my results too bad. I just want to debug the project in my compute.  please forgive my bad english.  hope your response ,thanks.

alright join where you want github dont allow to share more than 25mb
do you use telegram?

if you don't want to ise telegram then jump to **kaggle** link and in the output section you can see saved weight and model files
saved weight works like 🔥 so check it out

**Comment by Turing-dz** [comment]
Your method has solved my problem. Thank you very much
